name: Build MecchaCamouflage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        shell: powershell
        working-directory: MecchaCamouflage
        run: |
          ./scripts/build.ps1

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: meccha-camouflage
          path: MecchaCamouflage/.build/bin/*
