name: Build Mecaca EXE

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - run: |
          mkdir build
          cl /EHsc /std:c++17 /Fe:build\Mecaca.exe *.cpp

      - uses: actions/upload-artifact@v4
        with:
          name: Mecaca-exe
          path: build/Mecaca.exe
